"""adiciona coluna ativo na tabela produtos

Revision ID: 35da104dc57c
Revises: b6d41482d08b
Create Date: 2026-07-23 20:36:21.830879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35da104dc57c'
down_revision = 'b6d41482d08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
