"""adiciona coluna preco_antigo na tabela produtos

Revision ID: 4fc8dbf9e346
Revises: 35da104dc57c
Create Date: 2026-07-23 20:50:18.374241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc8dbf9e346'
down_revision = '35da104dc57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_antigo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('preco_antigo')

    # ### end Alembic commands ###
